export const perfumes = [
    {
        id : 1,
        link : "public/images/1.webp",
        name : "blacko",
        salary : 500,
    },
    {
        id : 2,
        link : '/images/2.png',
        name : "sofhag",
        salary : 650,
    },
    {
        id : 3,
        link : '/images/3.jpg',
        name : "remlo",
        salary : 599,
    },
    {
        id : 4,
        link : '/images/4.jpg',
        name : "frantic",
        salary : 290,
    },
    {
        id : 5,
        link : '/images/5.jpg',
        name : "blue night",
        salary : 300,
    },
    {
        id : 6,
        link : '/images/6.jpg',
        name : "raheeg",
        salary : 600,
    },
    {
        id : 7,
        link : '/images/7.jpg',
        name : "raheeg",
        salary : 600,
    },
    {
        id : 8,
        link : '/images/10.jpg',
        name : "elharamien",
        salary : 399,
    },
    {
        id : 9,
        link : '/images/8.jpg',
        name : "soft ",
        salary : 500,
    },
    {
        id : 10,
        link : '/images/9.jpg',
        name : "lialena",
        salary : 440,
    },{
        id : 11,
        link : '/images/11.jpg',
        name : "black",
        salary : 500,
    },
    {
        id : 12,
        link : '/images/12.webp',
        name : "sofhag",
        salary : 650,
    },
    {
        id : 13,
        link : '/images/13.webp',
        name : "remlo",
        salary : 599,
    },
    {
        id : 14,
        link : '/images/14.webp',
        name : "frantic",
        salary : 290,
    },
    {
        id : 15,
        link : '/images/15.jpeg',
        name : "blue night",
        salary : 300,
    },
    {
        id : 16,
        link : '/images/16.jpeg',
        name : "raheeg",
        salary : 600,
    },
    {
        id : 17,
        link : '/images/17.webp',
        name : "elharamien",
        salary : 399,
    },
    {
        id : 18,
        link : '/images/18.jpg',
        name : "soft ",
        salary : 500,
    },
    {
        id : 19,
        link : '/images/19.jpg',
        name : "lialena",
        salary : 440,
    },
    {
        id : 20,
        link : '/images/20.jpg',
        name : "lialena",
        salary : 440,
    }
]